<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cmd</string>
		<string>bat</string>
	</array>
	<key>name</key>
	<string>Batch File</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.batch</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>string.quoted.other.batch</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*@</string>
			<key>name</key>
			<string>keyword.operator.no-echo.batch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(not)\b</string>
			<key>name</key>
			<string>keyword.operator.batch</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.batch</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.path-subsitution.batch</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\%(((~(f|d|p|n|x|s|a|t|z|dp|nx|fs|ftza)?)?[0-9])|\*)</string>
			<key>name</key>
			<string>meta.variable.parameter.batch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\%\%[a-zA-Z]</string>
			<key>name</key>
			<string>variable.iterator.batch</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\brem\b.*</string>
			<key>name</key>
			<string>comment.line.rem.batch</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.command.internal.batch</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.other.batch</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(goto)\s+(\:?\w+)</string>
			<key>name</key>
			<string>meta.goto.batch</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.command.internal.batch</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.echo.batch</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(echo)\s+(on|off)</string>
			<key>name</key>
			<string>meta.echo.batch</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(net)\b\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.command.external.batch</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.net.commands.batch</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.net</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)\b(accounts|computer|config(?:\s+(?:server|workstation))?|continue|file|group|help(?:\s+(?:services|syntax))|helpmsg|localgroup|name|pause|print|send|session|share|start|statistics|stop|time|use|user|view)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.net-command.batch</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)if\s+((not)\s+)?(exist|defined|errorlevel|cmdextversion)\b</string>
			<key>name</key>
			<string>keyword.control.conditional.if.batch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(call|for|goto|if)\b</string>
			<key>name</key>
			<string>keyword.control.batch</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>These need to move into specific commands, like meta.for</string>
			<key>match</key>
			<string>(?i)\b(in|do)\b</string>
			<key>name</key>
			<string>support.control.batch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(assoc|chdir|cd|cls|color|copy|date|dir|dpath|echo|endlocal|erase|del|exit|ftype|mkdir|md|move|path|pause|popd|prompt|pushd|rem|rename|ren|rmdir|rd|set|setlocal|shift|start|time|title|type|ver)\b</string>
			<key>name</key>
			<string>keyword.command.internal.batch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(python)\b</string>
			<key>name</key>
			<string>support.other.tool.batch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(:.+)</string>
			<key>name</key>
			<string>entity.name.label.batch</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*:\s*:.*$</string>
			<key>name</key>
			<string>comment.line.colons.batch</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>\%(\w+)(:~\d+(,\d+)?)?\%</string>
			<key>name</key>
			<string>variable.other.batch</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.batch</string>
	<key>uuid</key>
	<string>195F743C-6EDD-4E9C-A6E3-163B09D8C86B</string>
</dict>
</plist>
